---
abstract: 'Basic HTTP authentication with htpasswd files in Dancer apps'
author:
  - 'Michal Wojciechowski <odyniec@cpan.org>'
build_requires:
  Pod::Readme: 0
  Pod::Select: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Plugin-Auth-Htpasswd
provides:
  Dancer::Plugin::Auth::Htpasswd:
    file: lib/Dancer/Plugin/Auth/Htpasswd.pm
    version: 0.01
requires:
  Authen::Htpasswd: 0
  Dancer: 1.307
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/odyniec/Dancer-Plugin-Auth-Htpasswd
version: 0.01
